#!/usr/bin/env bash
## Install nginx and configure homepage with exact required content
#
#apt-get update -y
#apt-get install nginx -y
#
#echo "Holberton School" > /var/www/html/index.html
#
#service nginx restart
#
