#!/usr/bin/env bash
## Install nginx and set up a custom page
#
## Install nginx silently
apt-get update -y
apt-get install nginx -y
#
## Make sure Nginx is running
service nginx start
#
## Replace the default page content with required string
echo 'Holberton School for the win!' > /var/www/html/index.nginx-debian.html
#
## Done!
#
