#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me

apt-get update -y
apt-get install nginx -y

# Configure redirect
sed -i '/ubuntu_;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

service nginx restart
